version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: m13
      POSTGRES_PASSWORD: 13052005Mm$
      POSTGRES_DB: PI_FashionHair
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: